### ISSUE TITLE
Growing array size in infer_data_builder function

### ISSUE THREAD

**Issue by Kenichiro-Yoshimi** [seiichiinoue/cnn-for-musical-onset-detection#3]
Hi, Firstly, thanks for a nice work. 

Currently, in the infer program, every time infer_data_builder() is called, the returned array size is actually increasing. Is it a correct behavior of the program? I think that it is necessary to erase an array x after each yield call like below.

```python
            if (i + 1) % minibatch == 0:
                yield (torch.from_numpy(np.array(x)).float())
                x = []
```
Note that I am on Windows 10 64-bit using Python 3.6 and Anaconda.

**Comment by seiichiinoue** [comment]
I'm sorry for late reply.
I'll check later, so please wait for a while.

**Comment by seiichiinoue** [comment]
Thank you for your advice. code has been reflected, so please check. If there are other deficiencies, please send additional pull requests. im sorry for late this time.

**Comment by Kenichiro-Yoshimi** [comment]
Thank you very much!!
