### ISSUE TITLE
TypeError: 'Audio' object is not iterable

### ISSUE THREAD

**Issue by realchrisolin** [seiichiinoue/cnn-for-musical-onset-detection#8]
```
python train.py don
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    net.train(songs=songs, minibatch=minibatch, val_song=None, epoch=epoch, device=device, soundlen=soundlen, save_place='./models/pytorch/don_model.pth', log='./data/log/pytorch/don.txt', don_ka=1)
  File "C:\Users\Chris Olin\PycharmProjects\onset_detection\cnn-for-musical-onset-detection\model.py", line 114, in train
    for song in songs:
TypeError: 'Audio' object is not iterable
```

**Comment by realchrisolin** [comment]
attaching this in case it helps someone troubleshoot in the future.
![image](https://user-images.githubusercontent.com/1288116/63276866-415a2d80-c272-11e9-8f9c-cebacfca0827.png)

**Comment by seiichiinoue** [comment]
`songs` must be list, but,  maybe you were using only one data for train, so raise up that kind of error. 
i recommend to use multiple data or put data in list like below
```
songs = [song]
net.train(songs=songs...
```

**Comment by realchrisolin** [comment]
I'm running into this issue following the steps in the README. admittedly, I've spent the better part of a few hours trying to debug this and started to wonder if `songs` needed to be a list (I initially thought the `Audio` class was supposed to be iterable), but I'm not sure where the additional songs/items in the list are supposed to come from.

`songs` is being instantiated by `pickle.load()`, so I'm not sure what the problem is here? Is the training data bad somehow? it's entirely possible I'm missing something that might be intuitive for someone more familiar with Python (still learning).

**Comment by seiichiinoue** [comment]
did you using `test_data` for training? `test_data` is for inference, so include only one song.
so, if you want to train, using `train_reduced` for training loop.
as a test, i tried running script, which changed `train_reduced` to `test_data` for training data, and result is below,
```
  File "train.py", line 27, in <module>
    net.train(songs=songs, minibatch=minibatch, val_song=None, epoch=epoch, device=device, soundlen=soundlen, save_place='./models/pytorch/don_model.pth', log='./data/log/pytorch/don.txt', don_ka=1)
  File "/Users/seiichi/Desktop/repositories/cnn-for-musical-onset-detection/model.py", line 114, in train
    for song in songs:
TypeError: 'Audio' object is not iterable
```
so, problem is pointed file.

**Comment by realchrisolin** [comment]
guess we can close this then. anyone else that runs into this issue needs to know that `songs` needs to be iterable.
